### ISSUE TITLE
do you know how can we get the file tableofcounts.txt directly?

### ISSUE THREAD

**Issue by xihajun** [YinCY123/Bioconductor#1]
for learning edgeR

**Comment by YinCY123** [comment]
I usually get count table by using biomaRt

发送自我的 Windows 10 设备

发件人: Junfan Huang
发送时间: 2020年2月4日 20:00
收件人: YinCY123/Bioconductor
抄送: Subscribed
主题: [YinCY123/Bioconductor] do you know how can we get the filetableofcounts.txt directly? (#1)

for learning edgeR

**Comment by xihajun** [comment]
Thanks

**Comment by YinCY123** [comment]
Sorry, I'm given you the wrong package name, actually I usually using GEOquery to get the count table from GEO database. The function is getGEOSuppfile()

发送自我的 Windows 10 设备

发件人: Junfan Huang
发送时间: 2020年2月4日 20:00
收件人: YinCY123/Bioconductor
抄送: Subscribed
主题: [YinCY123/Bioconductor] do you know how can we get the filetableofcounts.txt directly? (#1)

for learning edgeR
